repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch

  - repo: local
    hooks:
      - id: deno-lint
        name: deno lint
        entry: ./.git-hooks/pre-commit.lint.sh
        language: script

      - id: deno-check
        name: deno check
        entry: ./.git-hooks/pre-commit.check.sh
        language: script

      - id: deno-format
        name: deno format
        entry: ./.git-hooks/pre-commit.format.sh
        language: script
        pass_filenames: false
